windows_name = ""
window_activated = False
target_window = None
play_state = 'play' # play pause stop
thread = None
music_sheet = [] #乐谱
now_progress  = 0 #进度条
translate_progress = 0
overall_progress = 0
now_translate_text = []